//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaleMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicList
    {
        public int ListID { get; set; }
        public int MusicID { get; set; }
        public int UserID { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Music Music { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
