//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaleMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music()
        {
            this.MusicList = new HashSet<MusicList>();
        }
    
        public int MusicID { get; set; }
        public int SingerID { get; set; }
        public int TypeID { get; set; }
        public string MusicImage { get; set; }
        public string MusicName { get; set; }
        public string MusicCountry { get; set; }
        public System.DateTime MusicDate { get; set; }
        public string MusicFiles { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Singer Singer { get; set; }
        public virtual MusicType MusicType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicList> MusicList { get; set; }
    }
}
